# Generated by Django 4.2.3 on 2023-07-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortener',
            old_name='time_followed',
            new_name='times_followed',
        ),
        migrations.RemoveField(
            model_name='shortener',
            name='last_acceseed',
        ),
        migrations.AddField(
            model_name='shortener',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
